[build]
jobs = -1

[env]
RUST_BACKTRACE = "1"
# RUST_TEST_NOCAPTURE = "1"

[net]
retry = 3

[alias]
lint = "clippy --workspace --all-features -- -D warnings"
patch = "release patch --workspace --no-push"
minor = "release minor --workspace --no-push"
major = "release major --workspace --no-push"
